### ISSUE TITLE
Governance proposal for Competition prize pool

### ISSUE THREAD

**Issue by SenorMonito** [tendermint/liquidity#226]
By the end of this issue will have 5k ATOMS allocated from the Community Fund for the prize fund:

**Tasks**

- [x] Raise forum post with to get feedback (https://forum.cosmos.network/t/governance-community-fund-proposal-for-gravity-dex-prize-budget/4567/12)
- [x] Raise Governance proposal for completion on 21st April (https://www.mintscan.io/cosmos/proposals/45)
- [ ] Ensure Governance proposal passes
