### ISSUE TITLE
V1: Porting to based sdk v0.43.0 and v0.44.0 for vega upgrade

### ISSUE THREAD

**Issue by dongsam** [tendermint/liquidity#432]
Currently not clear when the Gaia upgrading schedule is based on SDK v0.43.x or v0.44.x
If that is soon, we need to start rebasing and porting in advance the current liquidity module based on SDK v0.43.x or v0.44.x

### liquidity v1.3.0 for Comos-SDK v0.43.0
- [x] https://github.com/tendermint/liquidity/issues/435 @dongsam @hallazzang 
- [x] [v0.43.0](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.43.0) https://github.com/tendermint/liquidity/pull/433 @dongsam @hallazzang @kogisin 
- [x] app-level local test, integration test, upgrade simulation @hallazzang @kogisin @dongsam 
- [x] Fix https://github.com/tendermint/liquidity/issues/437
- [x] Release a new version of the Liquidity module @dongsam 
  - [x] [v1.3.0-rc1](https://github.com/tendermint/liquidity/releases/tag/v1.3.0-rc1)
  - [x] [v1.3.0](https://github.com/tendermint/liquidity/releases/tag/v1.3.0) https://github.com/tendermint/liquidity/pull/439
- [x] rename package, push and release on gravity devs repo  https://github.com/gravity-devs/liquidity https://github.com/Gravity-Devs/liquidity/pull/2 @dongsam 
  - [x] [v1.3.0-rc1](https://github.com/Gravity-Devs/liquidity/releases/tag/v1.3.0-rc1)
  - [x] [v1.3.0](https://github.com/Gravity-Devs/liquidity/releases/tag/v1.3.0)
- [x] PR to Gaia https://github.com/cosmos/gaia/pull/942 https://github.com/cosmos/gaia/pull/956 @dongsam 
- [x] upgrade simulation test based exported states of cosmoshub-4 https://github.com/b-harvest/gravity-dex-upgrade-test https://github.com/tendermint/liquidity/issues/434 @kogisin @dongsam 
  - [x] v1.3.0-rc1
  - [x] v1.3.0

-------

### liquidity v1.4.0 for Comos-SDK v0.44.0
- [x] bump sdk version to v0.44.0 on `tendermint/liquidity/develop` 
   - [x] #441 
- [x]  merge develop to master of `tendermint/liquidity` 
   - [x] #442 
- [x]  release `v1.4.0` on `tendermint/liquidity/master`
- [x]  PR and push to [`gravity-devs/liquidity`](https://github.com/gravity-devs/liquidity/tree/gravity-devs-v1.4.0-candidate) and merge to `gravity-devs/master` and release `v1.4.0`
   - [x] [v1.4.0](https://github.com/Gravity-Devs/liquidity/releases/tag/v1.4.0)
- [x]  bump liquidity version to `v1.4.0` on [`gravity-dex`](https://github.com/b-harvest/gravity-dex/tree/upgrade-liquidity-module-based-sdk-43) for testing 
- [x]  upgrade simulation test based exported states of `cosmoshub-4`  with the `gravity-dex` gaia 
   - [x] https://github.com/b-harvest/gravity-dex-upgrade-test/pull/4
- [x]  add commit or PR for bump liquidity version to `v1.4.0` on `gaia`
   - [x] [gaia #956](https://github.com/cosmos/gaia/pull/956)
- [ ] Make sure there are no other issues.

Ref
- https://github.com/cosmos/cosmos-sdk/compare/v0.42.6...v0.43.0
- https://github.com/cosmos/cosmos-sdk/compare/v0.43.0...v0.44.0
- https://github.com/tendermint/liquidity/tree/porting-sdk-43-beta1
- https://github.com/tendermint/liquidity/pull/343
- https://github.com/cosmos/ibc-go/releases/tag/v1.0.0
